export const ACTIONS = {
  ADD_TAG: 'ADD_TAG',
  EDIT_TAG: 'EDIT_TAG',
  DELETE_TAG: 'DELETE_TAG',
  ASSOCIATE_TAG_TO_GIST: 'ASSOCIATE_TAG_TO_GIST',
  REMOVE_TAG_FROM_GIST: 'REMOVE_TAG_FROM_GIST',
  SET_TAGS_DATA: 'SET_TAGS_DATA',
  CHANGE_CURRENT_TAGS: 'CHANGE_CURRENT_TAGS',
  OPEN_ADD_TAG: 'OPEN_ADD_TAG',
  OPEN_ADD_TAG_EDIT_LABEL: 'OPEN_ADD_TAG_EDIT_LABEL',
  OPEN_ADD_TAG_EDIT_COLOR: 'OPEN_ADD_TAG_EDIT_COLOR'
};
